CREATE SEQUENCE disciplina_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE professor_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE horario_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE curso_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE coordenador_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE aluno_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE matriz_curricular_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE matricula_seq START WITH 1 INCREMENT BY 50;
