services:
  postgres:
    image: postgres:16-alpine
    container_name: get_matriculas-db
    environment:
      POSTGRES_DB: get_matriculas
      POSTGRES_USER: administrathor
      POSTGRES_PASSWORD: alunox789xyz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrador -d get_matriculas"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
