quarkus.datasource.username=administrathor
quarkus.datasource.password=alun0x789xyz
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/get_matriculas

quarkus.oidc.auth-server-url=http://localhost:8180/realms/get-matriculas

quarkus.http.cors.origins=http://localhost:4200

quarkus.swagger-ui.always-include=true
