quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true

quarkus.oidc.client-id=get-matriculas-back
quarkus.oidc.application-type=service
quarkus.oidc.token.principal-claim=sub
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

quarkus.smallrye-openapi.info-title=Gestão de Matrículas API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.oauth-client-id=get-matriculas-front

%test.quarkus.oidc.enabled=false
