quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=administrathor
quarkus.datasource.password=alunox789xyz
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/get_matriculas

quarkus.hibernate-orm.database.generation=update
