quarkus.datasource.username=${DB_USERNAME:administrathor}
quarkus.datasource.password=${DB_PASSWORD:alun0x789xyz}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:get_matriculas}

quarkus.oidc.auth-server-url=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8180}/realms/get-matriculas

quarkus.http.cors.origins=http://localhost:4200

quarkus.swagger-ui.always-include=true
